apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: develop
  name: pod-reader
rules:
- apiGroups: ["apps",""] # "" indicates the core API group
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: develop
subjects:
- kind: User
  name: eks-log-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
